<Project Sdk="Godot.NET.Sdk/4.7.1-outpostia.3">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <GodotDisabledAnalyzers>MustBeVariantAnalyzer</GodotDisabledAnalyzers>
  </PropertyGroup>
</Project>
